function f1 = GUI_IBSI2_RM_comparision(dataCell)
% Radiomics results visualasiation for single volume.
%--------------------------------------------------------------------------
% dataCell array of ALL test results (1.a.1, 1.a.2 .... etc)
%
%--------------------------------------------------------------------------
% @uthor Pwhybra
%--------------------------------------------------------------------------

filterTests   = dataCell(:,1);
current_dataS = dataCell{1,2};

% initialise variables and panel sizes
%--------------------------------------------------------------------------
f1 = figure('Resize','off',...
    'MenuBar', 'none',...
    'Color',[0 0 0]./255,...
    'Renderer','opengl',...
    'NumberTitle','off','visible','on','Position',[508 333 288 138]);

% Selection Pannel
%--------------------------------------------------------------------------
buttonW = 0.1;
deltaX = 0.01;
fontN = 'Calibri';
panelW = (1-3*deltaX);
panelH = (1-2*deltaX);

Selection_panel = uipanel('Units','Pixels',...
    'FontName',fontN,...
    'Units','normalized',...
    'BackgroundColor',[0,0,0],...
    'BorderType','etchedin',...
    'ForegroundColor','w',...
    'Title','Select Filter Test',...
    'FontSize',12,...
    'Position',[deltaX,deltaX,panelW,panelH]);

launch_button = uicontrol('Parent',Selection_panel,...
    'Style','pushbutton',...
    'Callback',@launch_button_Callback,...
    'BackgroundColor','w',...
    'String','launch',...
    'FontSize',12,...
    'Units','normalized',...
    'Tag','slice',...
    'UserData',-1,...
    'Position',[0.4,0.3,0.2,0.2]);

% Drop down menus
%--------------------------------------------------------------------------
menu_selection = uicontrol('Parent',Selection_panel,...
    'Style','popupmenu',...
    'BackgroundColor',[1,1,1],...
    'Callback',@menu_selection_Callback,...
    'FontSize',12,...
    'String',filterTests,...
    'Units','normalized',...
    'Position',[buttonW,0,0.8,0.85]);


    function menu_selection_Callback(source, eventdata)
        contents = get(source,'String');
        newRM_name = contents{get(source,'Value')};
        indx = find(contains(dataCell(:,1),newRM_name));
        current_dataS = dataCell{indx,2};
    end

    function  launch_button_Callback(source, eventdata)
        GUI_responseMapComparison2(current_dataS);
    end

end


